### PR TITLE
Imfv283

### PR DESCRIPTION
**Pull request by hasimpson-usgs**

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
Controller
- is the `input-goes-server` default public facing?

Observatory Metadata
- Change `DHT` name to be `Deadhorse Test` for consistency

GOESIMFV283Factory
- only import Stream from obspy.core
- constructor default for interval should be lower-cased, right?
- make `getdcpmessages` be the full path (instead of later appending getDcpMessages).
- where is `self.datetime` used?
- `_set_log_filename` and `_set_criteria_filename` don't seem like they need to be methods
- in `get_timeseries`, `channels`, `type`, and `interval` aren't used
- since this subclasses IMFV283Factory, can you just call `self.parse_string`?
- use an array of arguments when calling `check_output` in case `directory` contains spaces
- do files in `./opendcs/netlist/` need to be configured first?

IMFV283Factory
- `subprocess` import isn't needed

**Comment by hasimpson-usgs** [comment]
While I make the other changes....

The 'NETWORK_LIST' (./opendcs/netlist) can be uploaded to the server before
hand,  or uploaded each time getDcpMessage is called.
I don't upload them everytime because it takes extra time.  It's not much,
 but it is measurable.  Maybe a second or so per call.
I can put them in any "directory" I want to,  as the server doesn't care,
 I think it's just a name in their database,  although it may not be.
What's being done should probably be changed, as having a non-existent
directory hardcoded into the code doesn't make much sense.

Also,  yes the input-goes-server IS public facing.


On Thu, Nov 19, 2015 at 12:19 PM, Jeremy Fee <notifications@github.com>
wrote:

> Controller
>
>    - is the input-goes-server default public facing?
>
> Observatory Metadata
>
>    - Change DHT name to be Deadhorse Test for consistency
>
> GOESIMFV283Factory
>
>    - only import Stream from obspy.core
>    - constructor default for interval should be lower-cased, right?
>    - make getdcpmessages be the full path (instead of later appending
>    getDcpMessages).
>    - where is self.datetime used?
>    - _set_log_filename and _set_criteria_filename don't seem like they
>    need to be methods
>    - in get_timeseries, channels, type, and interval aren't used
>    - since this subclasses IMFV283Factory, can you just call
>    self.parse_string?
>    - use an array of arguments when calling check_output in case directory
>    contains spaces
>    - do files in ./opendcs/netlist/ need to be configured first?
>
> IMFV283Factory
>
>    - subprocess import isn't needed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/usgs/geomag-algorithms/pull/50#issuecomment-158163037>
> .
>



-- 
Hal Simpson
IT Specialist
USGS Geomagnetism Program
Office:303-273-8459
Email:hasimpson@usgs.gov

**Comment by hasimpson-usgs** [comment]
Changes made,  and pushed up.

**Comment by jmfee-usgs** [comment]
GOESIMFV283Factory
- in `get_timeseries`, `channels` `type` and `interval` are unused so `X = X or self.X` should be removed.

Add a documentation page about how to set up opendcs so it works, including:
- downloading opendcs
- uploading network list files
- using the goes input factory with geomag.py

Does the factory need to clean up any files after retrieving goes output?

Fix coding standard issues:
```
$ grunt
Running "flake8:src" (flake8) task
>> bin/geomag.py ... pass
>> bin/main.py ... pass
>> geomagio/AlgorithmException.py ... pass
>> geomagio/StreamConverter.py ... pass
>> geomagio/ChannelConverter.py ... pass
>> geomagio/DeltaFAlgorithm.py ... pass
>> geomagio/Controller.py ... fail
>> geomagio/Controller.py:223:17: E123 closing bracket does not match indentation of opening bracket's line
>> geomagio/Algorithm.py ... pass
>> bin/__init__.py ... pass
>> geomagio/ObservatoryMetadata.py ... pass
>> geomagio/TimeseriesFactory.py ... pass
>> geomagio/TimeseriesFactoryException.py ... pass
>> geomagio/Util.py ... pass
>> geomagio/TimeseriesUtility.py ... pass
>> geomagio/XYZAlgorithm.py ... pass
>> geomagio/__init__.py ... pass
>> geomagio/edge/RawInputClient.py ... pass
>> geomagio/edge/__init__.py ... pass
>> geomagio/edge/EdgeFactory.py ... pass
>> geomagio/iaga2002/IAGA2002Factory.py ... pass
>> geomagio/iaga2002/IAGA2002Parser.py ... pass
>> geomagio/iaga2002/IAGA2002Writer.py ... pass
>> geomagio/iaga2002/MagWebFactory.py ... pass
>> geomagio/iaga2002/StreamIAGA2002Factory.py ... pass
>> geomagio/iaga2002/__init__.py ... pass
>> geomagio/imfv283/GOESIMFV283Factory.py ... fail
>> geomagio/imfv283/GOESIMFV283Factory.py:4:1: F401 'datetime' imported but unused
>> geomagio/imfv283/GOESIMFV283Factory.py:41:42: E241 multiple spaces after ','
>> geomagio/imfv283/GOESIMFV283Factory.py:65:19: E221 multiple spaces before operator
>> geomagio/imfv283/GOESIMFV283Factory.py:66:17: E113 unexpected indentation
>> geomagio/imfv283/GOESIMFV283Factory.py:90:80: E501 line too long (89 > 79 characters)
>> geomagio/imfv283/GOESIMFV283Factory.py:107:9: E303 too many blank lines (2)
>> geomagio/imfv283/GOESIMFV283Factory.py:126:80: E501 line too long (89 > 79 characters)
>> geomagio/imfv283/GOESIMFV283Factory.py:139:9: F841 local variable 'start' is assigned to but never used
>> geomagio/imfv283/GOESIMFV283Factory.py:149:57: E502 the backslash is redundant between brackets
>> geomagio/imfv283/GOESIMFV283Factory.py:150:44: E502 the backslash is redundant between brackets
>> geomagio/imfv283/IMFV283Parser.py ... fail
>> geomagio/imfv283/IMFV283Parser.py:95:58: F841 local variable 'e' is assigned to but never used
>> geomagio/imfv283/IMFV283Factory.py ... pass
>> geomagio/imfv283/__init__.py ... fail
>> geomagio/imfv283/__init__.py:7:1: F401 'GOESIMFV283Factory' imported but unused
>> geomagio/imfv283/__init__.py:8:1: F401 'IMFV283Factory' imported but unused
>> geomagio/imfv283/StreamIMFV283Factory.py ... pass
>> geomagio/imfv283/imfv283_codes.py ... pass
>> geomagio/pcdcp/PCDCPFactory.py ... pass
>> geomagio/pcdcp/PCDCPParser.py ... pass
>> geomagio/pcdcp/StreamPCDCPFactory.py ... pass
>> geomagio/pcdcp/PCDCPWriter.py ... pass
>> geomagio/pcdcp/__init__.py ... pass
Warning: Task "flake8:src" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by hasimpson-usgs** [comment]
Ok,  one more round.

**Pull request merged**
