### PR TITLE
Use setuptools-pipfile so dependencies managed in pipfile

### PR DESCRIPTION
**Pull request by jmfee-usgs**
- use pipfile for pip dependencies
- support ssl intercept configuration if SSL_CERT_FILE environment configured
- move pre-commit to dev dependencies

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
@emartinez-usgs this seems to work for setuptools-pipfile

**Comment by erigler-usgs** [comment]
@jmfee-usgs , I think this looks good.

Even though it may not necessarily belong with this PR, I will ask if it makes sense to update `docs/install.md` to say something about pipenv. I know it is described in `docs/develop.md`, but shouldn't we have something that describes how non-developers might use it, kinda like we already do for conda in `docs/install.md`?

**Comment by jmfee-usgs** [comment]
@erigler-usgs I made a few changes in response to your comments.

**Comment by erigler-usgs** [comment]
Thanks. Your changes aren't quite what I was expecting, so I suspect I still lack some understanding of how pipenv is supposed to be used. I'll approve, merge, and ask you to re-educate me at a later date.

**Pull request merged**
