### PR TITLE
91

### LINKED ISSUE #91: Implement recursion limit for update flag.

### PR DESCRIPTION
**Pull request by hasimpson-usgs**
fixes #91

### CODE REVIEW

**Comment by hasimpson-usgs** [comment]
This adds a flag to limit the number of recursion steps in update.

**Comment by jmfee-usgs** [comment]
- remove debug print, or add debug option that disables it by default.
- change update_count to be an optional parameter to the run_as_update method, rather than a controller attribute, defaulting to zero.
- fix linting errors.

**Comment by hasimpson-usgs** [comment]
Changed and fixed per notes above.

**Comment by jmfee-usgs** [comment]
- self._update_count is not needed
- increment update_count when recursing (self.run_as_update(options, update_count + 1)), just return if at limit

**Comment by hasimpson-usgs** [comment]
Made suggested changes.

**Pull request merged**
